Repository containeroo/cloudflare-operator, pull requests merged in 2022-03, with the labels that each got.

#59 Metrics implementation
  controllers/account_controller.go
  controllers/common.go
  controllers/dnsrecord_controller.go
  controllers/ip_controller.go
  controllers/metrics.go
  controllers/zone_controller.go
  docs/content/installation.md
Labels: enhancement

#67 CO-58 Implement ip sources
  api/v1beta1/ip_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cf.containeroo.ch_ips.yaml
  controllers/ip_controller.go
  docs/content/installation.md
Labels: enhancement

#68 CO-61-update-docs-for-co-58
  docs/content/core_concept.md
  docs/content/getting_started.md
  docs/content/operations.md
  docs/content/upgrade_notes.md
Labels: documentation

#63 CO-48 Create Grafana dashboard
  config/manifests/grafana/dashboards/overview.json
  config/prometheus/monitor.yaml
  docs/content/monitoring.md
  docs/content/operations.md
  docs/mkdocs.yml
Labels: documentation, enhancement

#69 Fix logging, rename responeTextRegex to responseRegex
  api/v1beta1/ip_types.go
  config/crd/bases/cf.containeroo.ch_ips.yaml
  controllers/ip_controller.go
  docs/content/core_concept.md
  docs/content/installation.md
Labels: bug, documentation, enhancement

#76 Fix ip sample
  config/samples/cf_v1beta1_ip.yaml
Labels: documentation
